### ISSUE TITLE
use timezoned-date to force UTC at process level

### ISSUE THREAD

**Issue by kirrg001** [thorn0/timezoned-date#1]
Hey!

Thanks for this awesome npm module. Great work!

Did you ever use your module in production mode or for serious use cases?
My goal is to use your module in a bigger project to force UTC TZ on process level. 

````
global.Date = TimezonedDate.makeConstructor(0);
````

I've installed your module and my first impression is very very good, everything seems to work what i want to achieve. I've tested node-time, but it does not support windows.

I can see from your last commit, that ```test262: 399/449 passed, 50 failed``` that 50 tests failed. Can you give me input on that?

Thank you!

**Comment by thorn0** [comment]
Yes, it's used in production with jsdom to render emails using the code of an Angular app. The only shortcoming so far is that it doesn't support daylight saving time, so sometimes, after the clocks get adjusted, the users can see some incorrect values in their emails.

As for [test262](https://github.com/tc39/test262), many of those failing tests were unimportant edge cases and some others had time zone-related bugs themselves. However, the tests keep being worked on, and with the current version the number of passing tests is 434 of 495 (61 failed). You can run them yourself to see what fails. Clone this project and after doing `npm install`, run `npm run test262`.

**Comment by thorn0** [comment]
In particular, `Object.prototype.toString.apply(timezonedDateInstance)` doesn't return `'[object Date]'`, so e.g. lodash's `_.isDate` method won't return `true` for these objects.

**Comment by kirrg001** [comment]
Hey,

thanks for updating to 2.0.8.

There is one thing which does not work:
```
var lodash = require('lodash');
console.log(lodash.cloneDeep(new Date()))
{ date: [Function], offset: [Function] }
```

After cloning the Timezoned Object, its not an Timezoned Object anymore.

```
var x = lodash.cloneDeep(new Date());
console.log(moment(x).toDate());
Invalide Date
```

Thx,
Kate

**Comment by thorn0** [comment]
Can't reproduce this. Your example doesn't return `Invalid date` for me. 
`moment(lodash.cloneDeep(new Date())).toDate()` returns a valid instance of `TimezonedDate`.
Does it happen with 2.0.8? What versions of moment and lodash are you using?

**Comment by kirrg001** [comment]
timezoned-date 2.0.8
lodash 3.10.1
moment 2.13.0

**Comment by thorn0** [comment]
Previous time I tested it with lodash 4.x, but with 3.10.1 it works for me too. Here is the code I run:
```js
global.Date = require('timezoned-date').makeConstructor(0);
var moment = require('moment'), lodash = require('lodash');

var x = lodash.cloneDeep(new Date());
console.log(moment(x).toDate());
```

**Comment by kirrg001** [comment]
Installed lodash@4.12.0 - works.
Tested again with 3.10.1 - doesn't work.

But anyway, it works with a newer lodash version. Thanks!

**Comment by thorn0** [comment]
What are your Node version, OS and local time zone?

**Comment by kirrg001** [comment]
v4.4.2
OS MacOSX
GMT +02:00

**Comment by thorn0** [comment]
I was testing on Windows, Node 6.2. Tried other Node versions here: https://tonicdev.com/573e4af1e1387d1100253136/tz
and it seems to work.

Do you get this error with Lodash 3.10.1 if you run exactly the same code as in my message above?

**Comment by kirrg001** [comment]
Yes i copied it in a new js file and executed it.

**Comment by thorn0** [comment]
Okay, I'll look into it some time soon. I've just I found a more serious bug in this module. In its implementation of the `toString()` method, it uses native `Date.prototype.toString()`. But there are values that never can be rendered with this native method if the system time zone observes DST. E.g. in the tz where I'm now, I see this:
```
> Date0 = require('.').makeConstructor(0);
[Function: _TimezonedDate]
> d = new Date0(2015, 9, 25)
Sun Oct 25 2015 00:00:00 GMT+0000
> d.setHours(1)
Sun Oct 25 2015 02:00:00 GMT+0000
> d.setHours(2)
Sun Oct 25 2015 03:00:00 GMT+0000
> d.setHours(3)
Sun Oct 25 2015 03:00:00 GMT+0000
```
So I'm reimplementing `toString` for it to not use the native method.

**Comment by kirrg001** [comment]
There is another issue:

```
global.Date = require('timezoned-date').makeConstructor(0);
console.log(new Date().toUTCString()).
Invalid Date
```

**Comment by thorn0** [comment]
This method indeed didn't work. Good catch! I published 2.0.10, which fixes this. But does this code really output `Invalid Date` on your machine? For me, it throws a `TypeError`.

**Comment by kirrg001** [comment]
Yes type error, but i fixed the return object property value, i played a
bit with your code

**Comment by thorn0** [comment]
It turns out `Symbol.toStringTag` is supported only starting from Node 6, so we can't fool `Object.prototype.toString` this way on earlier versions of Node. Hence that issue with Lodash 3 on Node 4. It works on Tonic because they use polyfills there (core-js most probably) and override `Object.prototype.toString`.

There is a way around it without using polyfills I think, but it involves quite considerable rewriting of code.

**Comment by kirrg001** [comment]
Ok thanks for update and new version 2.0.10. Tested it, works so far. (i kept lodash 3 and only monkey patched deepClone from 4.x).

Any other concerns/bugs/problems you can think of?

**Comment by kirrg001** [comment]
I assume all these fn ```['toTimeString', 'toLocaleString', 'toLocaleDateString', 'toDateString', 'toLocaleTimeString']``` will not work and need implementation.

**Comment by thorn0** [comment]
Those with "locale" in the name work. The others don't.

**Comment by thorn0** [comment]
Implemented them in 2.0.11. As for

> Any other concerns/bugs/problems you can think of?

1) There is an issue with milliseconds on Node 6:
```js
var Date0=require('timezoned-date').makeConstructor(0);
var nativeDate = new Date; nativeDate.setMilliseconds(123);
var date0 = new Date0; date0.setMilliseconds(123);
var e;
e = new Date(nativeDate); // the native Date constructor called with a native Date instance
console.log(e.getMilliseconds()); // 123
e = new Date(date0); // the native Date constructor called with a TimezonedDate instance
console.log(e.getMilliseconds()); // 0 on Node 6
```

2) If your app uses the `vm` module, `global.Date = ...` doesn't have any influence on new contexts. You'll need to remember to override it there too.

**Comment by kirrg001** [comment]
Hey thanks for 2.0.12.
Another small issue i found:

```
new Date('2016-05-23 08:01:00').should.eql('2016-05-23T06:01:00.000Z');
```

```
expected TimezonedDate { 2016-05-23 06:01:00.000 -0000 offset: Function { name: '' } } to equal '2016-05-23T06:01:00.000Z'
```

**Comment by kirrg001** [comment]
And another small representation thingy:

When i set my system time to UTC:
```
console.log(lodash.cloneDeep(new Date('2016-05-21 09:00:01')));
Sat May 21 2016 09:00:01 GMT+0000 (UTC)
```
When i reset to local time (+2) and use your module:
```

console.log(lodash.cloneDeep(new Date('2016-05-21 09:00:01')));
Sat May 21 2016 07:00:01 GMT+0000
```

The ```(UTC)``` is missing.

**Comment by kirrg001** [comment]
And another thing:

```
local time is +02:00
makeConstructor(-120)
console.log(new Date('2016-05-23 08:01:00').toJSON().should.eql('2016-05-23T08:01:00.000Z'));
2016-05-23T06:01:00.000Z
```

I expect 08:01:00 instead of 06:01:00.

**Comment by kirrg001** [comment]
toTimeString seems also broken:

```
local time is +02:00
makeConstructor(-120)

console.log(new Date('2016-01-01 00:00:00').toTimeString());
01:00:00 GMT+0200
```

**Comment by thorn0** [comment]
`new Date('2016-05-23 08:01:00')` shouldn't be parsed as UTC whereas new Date('2016-05-23') should. See http://dygraphs.com/date-formats.html

**Comment by thorn0** [comment]
Please check 2.0.13. I think I've fixed all of those issues. As for the time zone names, the modules doesn't know them, but you can pass them with the offset in a following way:
```js
var MyDate = TimezonedDate.makeConstructor({
  valueOf: function() { return 120 },
  toString: function() { return 'Ixania Summer Time' }
});
```

However, unfortunately, there still is [this thing](https://github.com/thorn0/timezoned-date/blob/7ec5d42edae19476595afff55d238446ea0a7190/test/constructor_test.js#L92).

**Comment by kirrg001** [comment]
Thanks for 2.0.13 - nice.
Only two tests fails in my project:

```
new Date().should.eql('XXXX');
expected Date { XXXXX offset: Function { name: '' } }
```

The representation here is not correct.

```
local time +02:00 (-120 minutes offset)
makeConstructor({ value: .... return 0; toString: ... return 'UTC' })
console.log(new Date('2016-05-23T07:59:16.000'))
Mon May 23 2016 09:59:16 GMT+0000 (UTC)
```

Shouldn't it keep the time ```07:59:16```?

**Comment by thorn0** [comment]
First of all, the offset for +02:00 is 120 minutes, not -120. The return values of native `Date#getTimezoneOffset` are negated for some reason. However, if you need a constructor with the +02:00 time zone, you should call `.makeConstructor(120)`.

**Comment by kirrg001** [comment]
Its -120, because i am 2 hours ahead of UTC. GMT +02:00 is -120 offset.

**Comment by thorn0** [comment]
Okay, it depends on the point of view. IMHO if it's **plus** 02:00, then it should be plus 120. Anyway, that's how the API works:
```js
var MyDate = TimezonedDate.makeConstructor(120);
var date = new MyDate();
console.log(date.getTimezoneOffset()); // -120
```

**Comment by kirrg001** [comment]
Yeah point of view - correct!
Everything works perfect with setting makeConstructor(0), except of the last two issues.

**Comment by thorn0** [comment]
I can't understand the first issue. What does this XXXX mean? Why should it be equal to new Date()?

**Comment by kirrg001** [comment]
Sorry, my fault. XXXX was just a placeholder for any date.

```
makeConstructor(0);
new Date('2015-05-05').should.eql('Mon May 23 2016 00:00:00 GMT+0000 (UTC)')
```

It throws an exception:
```
AssertionError
expected Date { 2016-05-23 00:00:00.000 -0000 offset: Function { name: '' } } to equal '2016-05-23 09:59:16.000 -0000'
```

**Comment by thorn0** [comment]
So you are comparing a Date object with a string. It doesn't work with native Date objects either:
```js
new Date('2016-05-23').should.eql(new Date('2016-05-23').toString())
```

**Comment by thorn0** [comment]
As for the second issue, it's fixed in 2.0.14.

**Comment by kirrg001** [comment]
Thanks, works. I really appreciate your fast response and updates.

**Comment by kirrg001** [comment]
Will close for now!
